name: blog_app
description: "Implement Clean Arch | bloc | Supabase | Hive"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  supabase_flutter: ^2.3.4
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


